// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES
#include "RobotMap.h"
#include "LiveWindow/LiveWindow.h"
#include "ctre/Phoenix.h"
// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES
#include "WPILib.h"

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=ALLOCATION
std::shared_ptr<WPI_TalonSRX> RobotMap::driveTrainLeftFront;
std::shared_ptr<WPI_TalonSRX> RobotMap::driveTrainLeftBack;
std::shared_ptr<WPI_TalonSRX> RobotMap::driveTrainRightBack;
std::shared_ptr<WPI_TalonSRX> RobotMap::driveTrainRightFront;
std::shared_ptr<frc::SpeedController> RobotMap::intakeLeftRoller;
std::shared_ptr<frc::SpeedController> RobotMap::intakeRightRoller;
std::shared_ptr<frc::DigitalOutput> RobotMap::intakeLightOn;
std::shared_ptr<frc::DigitalInput> RobotMap::intakeRollerStopSensor;
std::shared_ptr<frc::SpeedController> RobotMap::armArmActuator;
std::shared_ptr<frc::AnalogPotentiometer> RobotMap::armArmPositionSensor;
std::shared_ptr<frc::SpeedController> RobotMap::climberClimberRelease;
//std::shared_ptr<frc::Compressor> RobotMap::climberClimberCompressor;
std::shared_ptr<frc::SpeedController> RobotMap::climberClimberPullMotor;
// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=ALLOCATION

void RobotMap::init() {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    frc::LiveWindow *lw = frc::LiveWindow::GetInstance();

    driveTrainLeftFront.reset(new WPI_TalonSRX(0));
    
    
    driveTrainLeftBack.reset(new WPI_TalonSRX(1));
    
    
    driveTrainRightBack.reset(new WPI_TalonSRX(3));
    
    
    driveTrainRightFront.reset(new WPI_TalonSRX(2));
    
    
    intakeLeftRoller.reset(new frc::VictorSP(0));
    //lw->AddActuator("Intake", "LeftRoller", std::static_pointer_cast<frc::VictorSP>(intakeLeftRoller));
    
    intakeRightRoller.reset(new frc::VictorSP(1));
    //lw->AddActuator("Intake", "RightRoller", std::static_pointer_cast<frc::VictorSP>(intakeRightRoller));
    
    intakeLightOn.reset(new frc::DigitalOutput(1));
    //lw->AddActuator("Intake", "LightOn", intakeLightOn);
    
    intakeRollerStopSensor.reset(new frc::DigitalInput(0));
    //lw->AddSensor("Intake", "RollerStopSensor", intakeRollerStopSensor);
    
    armArmActuator.reset(new frc::VictorSP(2));
    lw->AddActuator("Arm", "ArmActuator", std::static_pointer_cast<frc::VictorSP>(armArmActuator));
    
    /*
     * The Analog Potentiometer has 3 parameters. 1st is the Analog Port
     * on the Rio. 2nd is the Scale factor to return meaningful units.
     * From the documentation "The scaling to multiply the voltage by
     * to get a meaningful unit." Try this as 1.0 first since it should
     * already be in volts. It was at 2.4 and the values were always about
     * twice as large as should have been so it makes sense to keep it at 1.0.
     * If 1.0 does not work then change it to 5.0. The 3rd parameter is the
     * offset. We don't need to offset our voltage by anything so it is 0.0
     */

    armArmPositionSensor.reset(new frc::AnalogPotentiometer(0, 1.0, 0.0));
    lw->AddSensor("Arm", "ArmPositionSensor", armArmPositionSensor);
    
    climberClimberRelease.reset(new frc::VictorSP(4));
    //lw->AddActuator("Climber", "ClimberRelease", climberClimberRelease);
    
    //climberClimberCompressor.reset(new frc::Compressor(0));
    //lw->AddActuator("Climber", "ClimberCompressor", climberClimberCompressor);
    
    climberClimberPullMotor.reset(new frc::VictorSP(3));
    //lw->AddActuator("Climber", "ClimberPullMotor", std::static_pointer_cast<frc::VictorSP>(climberClimberPullMotor));
    

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS

   driveTrainLeftBack->Follow(*driveTrainLeftFront); //left back to follow left front
   driveTrainRightBack->Follow(*driveTrainRightFront); //right back to follow right front

   driveTrainLeftFront->SetSensorPhase(true); //Reverse sensors
   driveTrainRightFront->SetSensorPhase(true); //Reverse sensors

   driveTrainRightBack->SetInverted(true);
   driveTrainRightFront->SetInverted(true);

   driveTrainLeftFront->ConfigSelectedFeedbackSensor(FeedbackDevice::QuadEncoder, 0, kTimeoutMs);
   driveTrainRightFront->ConfigSelectedFeedbackSensor(FeedbackDevice::QuadEncoder, 0, kTimeoutMs);

   /* Configure PID_F for Closed Loop */

   driveTrainLeftFront->Config_kF(kSlotIDx_Cloop, kF_CloopLeft, kTimeoutMs);
   driveTrainLeftFront->Config_kP(kSlotIDx_Cloop, kP_CloopLeft, kTimeoutMs);
   driveTrainLeftFront->Config_kI(kSlotIDx_Cloop, kI_CloopLeft, kTimeoutMs);
   driveTrainLeftFront->Config_kD(kSlotIDx_Cloop, kD_CloopLeft, kTimeoutMs);

   driveTrainRightFront->Config_kF(kSlotIDx_Cloop, kF_CloopRight, kTimeoutMs);
   driveTrainRightFront->Config_kP(kSlotIDx_Cloop, kP_CloopRight, kTimeoutMs);
   driveTrainRightFront->Config_kI(kSlotIDx_Cloop, kI_CloopRight, kTimeoutMs);
   driveTrainRightFront->Config_kD(kSlotIDx_Cloop, kD_CloopRight, kTimeoutMs);

   /*Configure PID_F for Motion Profile */

   driveTrainLeftFront->Config_kF(kSlotIDx_Motion, kF_MotionLeft, kTimeoutMs);
   driveTrainLeftFront->Config_kP(kSlotIDx_Motion, kP_MotionLeft, kTimeoutMs);
   driveTrainLeftFront->Config_kI(kSlotIDx_Motion, kI_MotionLeft, kTimeoutMs);
   driveTrainLeftFront->Config_kD(kSlotIDx_Motion, kD_MotionLeft, kTimeoutMs);

   driveTrainRightFront->Config_kF(kSlotIDx_Motion, kF_MotionRight, kTimeoutMs);
   driveTrainRightFront->Config_kP(kSlotIDx_Motion, kP_MotionRight, kTimeoutMs);
   driveTrainRightFront->Config_kI(kSlotIDx_Motion, kI_MotionRight, kTimeoutMs);
   driveTrainRightFront->Config_kD(kSlotIDx_Motion, kD_MotionRight, kTimeoutMs);
}
