// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#ifndef _ROBOT_H
#define _ROBOT_H

#include "WPILib.h"
#include "Commands/Command.h"
#include "RobotMap.h"
#include "LiveWindow/LiveWindow.h"

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES
#include "Commands/PositionOneLeft.h"
#include "Commands/PositionOneRight.h"
#include "Commands/PositionTwoLeft.h"
#include "Commands/PositionTwoRight.h"
#include "Commands/PositionThreeLeft.h"
#include "Commands/PositionThreeRight.h"
#include "Commands/PositionOneLeftPath.h"
#include "Commands/PositionOneRightPath.h"
#include "Commands/PositionTwoLeftPath.h"
#include "Commands/PositionTwoRightPath.h"
#include "Commands/PositionThreeLeftPath.h"
#include "Commands/PositionThreeRightPath.h"
#include "Commands/DoNothingPath.h"
#include "Commands/DriveWithEncoders.h"
#include "Commands/DriveForward.h"
#include "Commands/WaitUntilReady.h"
#include "Subsystems/Arm.h"
#include "Subsystems/Climber.h"
#include "Subsystems/DriveTrain.h"
#include "Subsystems/Intake.h"
#include "Subsystems/MotionProfile.h"

// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES
#include "OI.h"

class Robot : public frc::TimedRobot {
public:
	frc::Command* autonomousCommand = nullptr;
	static std::unique_ptr<OI> oi;
	frc::LiveWindow *lw = frc::LiveWindow::GetInstance();
	frc::SendableChooser<std::string> chooser;
	std::string gameData;
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
	static std::shared_ptr<DriveTrain> driveTrain;
	static std::shared_ptr<MotionProfile> motionProfile;
	static std::shared_ptr<Intake> intake;
	static std::shared_ptr<Arm> arm;
	static std::shared_ptr<Climber> climber;
	// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
	void RobotInit() override;
	void DisabledInit() override;
	void DisabledPeriodic() override;
	void AutonomousInit() override;
	void AutonomousPeriodic() override;
	void TeleopInit() override;
	void TeleopPeriodic() override;



};
#endif
