// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#ifndef ROBOTMAP_H
#define ROBOTMAP_H

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES
#include "WPILib.h"
#include "ctre/Phoenix.h"
// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES

/**
 * The RobotMap is a mapping from the ports sensors and actuators are wired into
 * to a variable name. This provides flexibility changing wiring, makes checking
 * the wiring easier and significantly reduces the number of magic numbers
 * floating around.
 */
class RobotMap {
public:
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
	static std::shared_ptr<WPI_TalonSRX> driveTrainLeftFront;
	static std::shared_ptr<WPI_TalonSRX> driveTrainLeftBack;
	static std::shared_ptr<WPI_TalonSRX> driveTrainRightBack;
	static std::shared_ptr<WPI_TalonSRX> driveTrainRightFront;
	static std::shared_ptr<frc::SpeedController> intakeLeftRoller;
	static std::shared_ptr<frc::SpeedController> intakeRightRoller;
	static std::shared_ptr<frc::DigitalOutput> intakeLightOn;
	static std::shared_ptr<frc::DigitalInput> intakeRollerStopSensor;
	static std::shared_ptr<frc::SpeedController> armArmActuator;
	static std::shared_ptr<frc::AnalogPotentiometer> armArmPositionSensor;
	static std::shared_ptr<frc::Solenoid> climberClimberRelease;
	static std::shared_ptr<frc::Compressor> climberClimberCompressor;
	static std::shared_ptr<frc::SpeedController> climberClimberPullMotor;
	// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

	static void init();
};
#endif
