// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#include "DriveWithEncoders.h"

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR

DriveWithEncoders::DriveWithEncoders(): frc::Command() {
        // Use requires() here to declare subsystem dependencies
    // eg. requires(Robot::chassis.get());
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
	Requires(Robot::driveTrain.get());
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES

	m_done = false;

}// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR

// Called just before this Command runs the first time
void DriveWithEncoders::Initialize() {
	std::cout << "AUTODRIVEFORWARD" << std::endl;
	SetTimeout(7);
	m_done = false;
	Robot::driveTrain->encoderReset();
}

// Called repeatedly when this Command is scheduled to run
void DriveWithEncoders::Execute() {
Robot::driveTrain->encoderPosition(3000,3000);
Robot::driveTrain->isMove();
}

// Make this return true when this Command no longer needs to run execute()
bool DriveWithEncoders::IsFinished() {
    return m_done || IsTimedOut();
}

// Called once after isFinished returns true
void DriveWithEncoders::End() {
Robot::driveTrain->encoderDone();

}

// Called when another command which requires one or more of the same
// subsystems is scheduled to run
void DriveWithEncoders::Interrupted() {
End();
}
